context.modules = [
  { name = libpipewire-module-rtp-source
    args = {
      source.ip    = "0.0.0.0"
      source.port  = 9001
      sess.latency.msec = 50
      node.always-process = true
      sess.media   = "audio"
      audio.format = "S16BE"
      audio.rate   = 48000
      audio.channels = 2
      stream.props = {
        node.name  = "rtp-source"
        media.class = "Audio/Source"
      }
    }
    flags = [ ifexists nofail ]
  }
]
