context.modules = [
  { name = libpipewire-module-loopback
    args = {
      capture.props = {
        node.name        = "librespot-in"
        media.class      = "Audio/Sink"
        node.description = "Librespot Input"
      }
      playback.props = {
        node.name        = "librespot"
        media.class      = "Audio/Source"
        node.description = "Librespot (Spotify)"
      }
    }
    flags = [ ifexists nofail ]
  }
]
