context.modules = [
  { name = libpipewire-module-loopback
    args = {
      capture.props = {
        node.name        = "main-mix"
        media.class      = "Audio/Sink"
        node.description = "EchoMux Main Mix"
      }
      playback.props = {
        node.name        = "main-mix-source"
        media.class      = "Audio/Source"
        node.description = "EchoMux Main Mix Source"
        node.autoconnect = false
      }
    }
    flags = [ ifexists nofail ]
  }
]
