# echomux satellite configuration
# Deployed from Makefile.local (make deploy-satellite)

ECHOMUX_ADAPTER=hci1
ECHOMUX_ADDR=:56644
ECHOMUX_MODE=satellite
ECHOMUX_NAME=raspi
ECHOMUX_MASTER_ADDR=192.168.1.3:56644
ECHOMUX_DEBUG=true
